# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLjN7hqj9zPa-V9MgGooGcnIkNSUat28
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("imoore/60k-stack-overflow-questions-with-quality-rate")

print("Path to dataset files:", path)

import pandas as pd
import os

# List files in the downloaded directory to find the CSV file
file_list = os.listdir(path)
print("Files in the dataset directory:", file_list)

# Assuming there is a single CSV file, or picking the first one
csv_file = [f for f in file_list if f.endswith('.csv')][0]

# Construct the full path to the CSV file
csv_path = os.path.join(path, csv_file)

df = pd.read_csv(csv_path)
df.head()

df.info()

unique_tags = df["Tags"].nunique()
print("Number of unique tag combinations:", unique_tags)

from collections import Counter
import re # Import re for regex operations

# Function to parse tags string into a list of individual tags
def parse_tags(tags_string):
    if isinstance(tags_string, str):
        # Remove <> and split by >< to get individual tags
        return [tag.strip() for tag in re.findall(r'<(.*?)>', tags_string)]
    return []

# Extract and flatten all tags
all_tags = [tag for sublist in df["Tags"].apply(parse_tags) for tag in sublist]

tag_counts = Counter(all_tags)

# Convert to DataFrame
tag_df = pd.DataFrame(tag_counts.items(), columns=["Tag", "Count"])

# Sort descending
tag_df = tag_df.sort_values(by="Count", ascending=False)

tag_df.head(20)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,6))

sns.barplot(
    data=tag_df.head(20),
    x="Count",
    y="Tag"
)

plt.title("Top 20 Most Frequent Tags")
plt.xlabel("Frequency")
plt.ylabel("Tag")
plt.show()

df["num_tags"] = df["Tags"].apply(len)

plt.figure(figsize=(8,5))
sns.histplot(df["num_tags"], bins=10)

plt.title("Distribution of Number of Tags per Question")
plt.xlabel("Number of Tags")
plt.ylabel("Count")
plt.show()

df["CreationDate"] = pd.to_datetime(df["CreationDate"])

df["Year"] = df["CreationDate"].dt.year

questions_per_year = df["Year"].value_counts().sort_index()

plt.figure(figsize=(10,5))
questions_per_year.plot(kind="line")

plt.title("Questions per Year")
plt.xlabel("Year")
plt.ylabel("Number of Questions")
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt # Added import for plt

text = " ".join(all_tags)

wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white"
).generate(text)

plt.figure(figsize=(12,6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Tag Word Cloud")
plt.show()

!pip install wordcloud



df["text"] = df["Title"] + " " + df["Body"]

from sklearn.model_selection import train_test_split

X = df["text"]
y = df["Tags"] # Changed to use df["Tags"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
    # Removed stratify=y as it's problematic with many unique tag combinations
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=25000,
    stop_words="english",
    ngram_range=(1,2),
    min_df=3
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

from sklearn.svm import LinearSVC
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.multiclass import OneVsRestClassifier
import re

# Function to parse tags string into a list of individual tags
def parse_tags(tags_string):
    if isinstance(tags_string, str):
        # Remove <> and split by >< to get individual tags
        return [tag.strip() for tag in re.findall(r'<(.*?)>', tags_string)]
    return []

# Function to filter parsed tags, keeping only frequent ones
def filter_to_frequent_tags(parsed_tag_list, frequent_tags_set):
    return [tag for tag in parsed_tag_list if tag in frequent_tags_set]

# Define frequent_tags using tag_df (e.g., top 1000 frequent tags)
# tag_df is available from a previous cell.
frequent_tags = tag_df["Tag"].head(1000).tolist() # Assuming top 1000 tags are considered frequent.

# Transform y_train and y_test into lists of all parsed tags
y_train_parsed = y_train.apply(parse_tags)
y_test_parsed = y_test.apply(parse_tags)

# Convert frequent_tags list (defined in the previous cell) to a set for faster lookup
frequent_tags_set = set(frequent_tags)

# Filter y_train_parsed and y_test_parsed to include only frequent tags
y_train_filtered = y_train_parsed.apply(lambda x: filter_to_frequent_tags(x, frequent_tags_set))
y_test_filtered = y_test_parsed.apply(lambda x: filter_to_frequent_tags(x, frequent_tags_set))

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()
# Fit MLB only on the frequent tags to define its classes. This prevents warnings for very rare tags.
mlb.fit([frequent_tags])

y_train_multilabel = mlb.transform(y_train_filtered)
y_test_multilabel = mlb.transform(y_test_filtered)

# Train a OneVsRestClassifier with LinearSVC
model = OneVsRestClassifier(LinearSVC(class_weight="balanced", dual=False)) # Added dual=False for sparse data
model.fit(X_train_tfidf, y_train_multilabel)

from sklearn.metrics import f1_score, classification_report

y_pred_multilabel = model.predict(X_test_tfidf)

print("F1-score (micro):", f1_score(y_test_multilabel, y_pred_multilabel, average="micro"))
print("F1-score (macro):", f1_score(y_test_multilabel, y_pred_multilabel, average="macro"))
print("F1-score (weighted):", f1_score(y_test_multilabel, y_pred_multilabel, average="weighted"))

# You can also get a more detailed report for each label
# print(classification_report(y_test_multilabel, y_pred_multilabel, target_names=mlb.classes_))

import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully!")

def predict_tag(title, body):
    text = title + " " + body
    text_vec = vectorizer.transform([text])
    prediction_multilabel = model.predict(text_vec)
    # Convert multi-hot encoded prediction back to tag names
    predicted_tags = mlb.inverse_transform(prediction_multilabel)
    # inverse_transform returns a list of tuples, even for a single prediction
    # So we take the first element (which is a tuple of tags for the single input)
    return list(predicted_tags[0])

predict_tag(
    "How to merge two pandas dataframes?",
    "I have two dataframes and want to join them on a common column."
)

import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(pipeline, f)

print("Model saved successfully!")

import pickle

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Vectorizer saved successfully!")

pickle.dump(mlb, open("mlb.pkl", "wb"))



